# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="tmc5160",
    version="0.1.0",
    python_requires="==3.*,>=3.6.0",
    author="betaboon",
    author_email="betaboon@0x80.ninja",
    packages=["tmc5160"],
    package_dir={"": "."},
    package_data={},
    install_requires=["rpi-gpio==0.*,>=0.7.0", "spidev==3.*,>=3.5.0"],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "pytest==5.*,>=5.2.0"]},
)
